/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.RentalManagement;

import GUIUtility.Utility;
import PersonManagement.Customer;
import PersonManagement.Person;
import RentalManagement.Rental;
import static RentalManagementSystem.MainFrame.store;
import static RentalManagementSystem.MainFrame.employee;
import StockManagement.Car;
import StockManagement.Status;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanket
 */
public class RentCarIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form RentCarIFrame
     */
    public RentCarIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        newCustomerPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        newCustomerIdTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        telephonetextField = new javax.swing.JTextField();
        licenceNumberTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        birthDatePicker = new org.jdesktop.swingx.JXDatePicker();
        licenceExpiryDatePicker = new org.jdesktop.swingx.JXDatePicker();
        newCustomerRentButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        newCustomerCarRegistrationNumber = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        newCustomerDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        existingCustomerIdTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        existingCustomerCarRegistrationNumberTextField = new javax.swing.JTextField();
        ExistingCustomerRentButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        existingCustomerDueDatePicker = new org.jdesktop.swingx.JXDatePicker();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Rent Car");

        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Bell MT", 3, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel5.setText("Name");

        nameTextField.setName("Name"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel6.setText("Date of Birth");

        addressTextField.setName("Address"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel8.setText("Telephone Number");

        telephonetextField.setName("Telephone"); // NOI18N

        licenceNumberTextField.setName("Licence Number"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel9.setText("Licence Number");

        jLabel10.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel10.setText("Age");

        jLabel11.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel11.setText("Licence Expiry");

        newCustomerRentButton.setText("Rent");
        newCustomerRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerRentButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel12.setText("Car Registration Number");

        newCustomerCarRegistrationNumber.setName("Car Registration Number"); // NOI18N
        newCustomerCarRegistrationNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerCarRegistrationNumberActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel13.setText("Due Date");

        javax.swing.GroupLayout newCustomerPanelLayout = new javax.swing.GroupLayout(newCustomerPanel);
        newCustomerPanel.setLayout(newCustomerPanelLayout);
        newCustomerPanelLayout.setHorizontalGroup(
            newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(newCustomerRentButton)
                        .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(newCustomerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newCustomerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newCustomerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newCustomerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(newCustomerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newCustomerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telephonetextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newCustomerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(licenceNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newCustomerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newCustomerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(licenceExpiryDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(newCustomerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCustomerCarRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newCustomerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCustomerDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(754, Short.MAX_VALUE))
        );
        newCustomerPanelLayout.setVerticalGroup(
            newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newCustomerCarRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCustomerDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newCustomerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telephonetextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(licenceNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenceExpiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(newCustomerRentButton)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("New Customer", newCustomerPanel);

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel1.setText("Customer ID");

        existingCustomerIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingCustomerIdTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel2.setText("Car Registration Number");

        existingCustomerCarRegistrationNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingCustomerCarRegistrationNumberTextFieldActionPerformed(evt);
            }
        });

        ExistingCustomerRentButton.setText("Rent");
        ExistingCustomerRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExistingCustomerRentButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel3.setText("Due Date");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExistingCustomerRentButton)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(existingCustomerIdTextField)
                            .addComponent(existingCustomerCarRegistrationNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(existingCustomerDueDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(742, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(existingCustomerIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(existingCustomerCarRegistrationNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(existingCustomerDueDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ExistingCustomerRentButton)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Existing Customer", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void existingCustomerIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingCustomerIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existingCustomerIdTextFieldActionPerformed

    private void existingCustomerCarRegistrationNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingCustomerCarRegistrationNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existingCustomerCarRegistrationNumberTextFieldActionPerformed

    private void ExistingCustomerRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExistingCustomerRentButtonActionPerformed
        // TODO add your handling code here:
        String idInput = existingCustomerIdTextField.getText();
        boolean validId = Utility.checkIntegerInput(idInput);
        if (validId == true){
            boolean emptyField = true;
            String registrationNumberInput = existingCustomerCarRegistrationNumberTextField.getText();
            if (registrationNumberInput.length() == 0){
                JOptionPane.showMessageDialog(this, "Please enter car registration number");
            }
            else{
                emptyField = false;
            }

            if(emptyField == false){
                int id = Integer.parseInt(existingCustomerIdTextField.getText());
                String registrationNumber = existingCustomerCarRegistrationNumberTextField.getText();
                Date dueDate = existingCustomerDueDatePicker.getDate();

                Car car = employee.searchCarByRegistrationNumber(store, registrationNumber);
                Person person = employee.searchPersonById(id, store);
                if (car == null){
                    JOptionPane.showMessageDialog(this, "No car found with the registration number entered");
                }
                else if (person == null){
                    JOptionPane.showMessageDialog(this, "No customer found with the ID entered");
                }
                else{
                    if(car.getStatus() == Status.Available){
                        if(person instanceof Customer){
                            Customer customer = (Customer) person;
                            Rental rental = new Rental(car, customer, dueDate);
                            employee.rentCar(rental, store, car, customer);
                            JOptionPane.showMessageDialog(this, "Car rented successfully");
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "No customer found with the ID entered");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Sorry this car is not available for renting");
                    }
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please enter a number for customer ID");
        }
        
    }//GEN-LAST:event_ExistingCustomerRentButtonActionPerformed

    private void newCustomerCarRegistrationNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerCarRegistrationNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCustomerCarRegistrationNumberActionPerformed

    private void newCustomerRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerRentButtonActionPerformed
        // TODO add your handling code here:
        String idInput = newCustomerIdTextField.getText();
        String ageInput = ageTextField.getText();
        boolean validId = Utility.checkIntegerInput(idInput);
        boolean validAge = Utility.checkIntegerInput(ageInput);
        if(validId == true && validAge == true){
            Hashtable<String,String> data = Utility.readData(newCustomerPanel);
            int id = Integer.parseInt(newCustomerIdTextField.getText());
            int age = Integer.parseInt(ageTextField.getText());
            Date licenceExpiry = licenceExpiryDatePicker.getDate();
            Date dob = birthDatePicker.getDate();
            Date dueDate = newCustomerDatePicker.getDate();
            
            String output = Utility.checkEmptyField(data);
            if (output.length() != 0){
                JOptionPane.showMessageDialog(this, output);
            }
            
            else{
                Customer cust = new Customer(data.get("Licence Number"), age, licenceExpiry, id, data.get("Name"), dob, data.get("Address"), data.get("Telephone"));
                employee.addPerson(store, cust);
                Car car = employee.searchCarByRegistrationNumber(store, data.get("Car Registration Number"));
                Person person = employee.searchPersonById(id, store);
                if (car == null){
                    JOptionPane.showMessageDialog(this, "No car found with the registration number entered");
                }
                else if (person == null){
                    JOptionPane.showMessageDialog(this, "No customer found with the ID entered");
                }
                else{
                    if(car.getStatus() == Status.Available){
                        if(person instanceof Customer){
                            Customer customer = (Customer) person;
                            Rental rental = new Rental(car, customer, dueDate);
                            employee.rentCar(rental, store, car, customer);
                            JOptionPane.showMessageDialog(this, "Car rented successfully");
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "No customer found with the ID entered");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Sorry this car is not available for renting");
                    }
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please enter only numbers for age and ID fields");
        }
    }//GEN-LAST:event_newCustomerRentButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExistingCustomerRentButton;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField ageTextField;
    private org.jdesktop.swingx.JXDatePicker birthDatePicker;
    private javax.swing.JTextField existingCustomerCarRegistrationNumberTextField;
    private org.jdesktop.swingx.JXDatePicker existingCustomerDueDatePicker;
    private javax.swing.JTextField existingCustomerIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXDatePicker licenceExpiryDatePicker;
    private javax.swing.JTextField licenceNumberTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField newCustomerCarRegistrationNumber;
    private org.jdesktop.swingx.JXDatePicker newCustomerDatePicker;
    private javax.swing.JTextField newCustomerIdTextField;
    private javax.swing.JPanel newCustomerPanel;
    private javax.swing.JButton newCustomerRentButton;
    private javax.swing.JTextField telephonetextField;
    // End of variables declaration//GEN-END:variables
}
