/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentalManagementSystem;

import GUI.PersonManagement.AddEmployeeIFrame;
import GUI.PersonManagement.ShowPersonDetailsIFrame;
import GUI.PersonManagement.UpdatePersonDetails;
import GUI.RentalManagement.RentCarIFrame;
import GUI.RentalManagement.ReturnCarIFrame;
import GUI.RentalManagement.ShowCustomerRentalsIFrame;
import GUI.RentalManagement.ShowRentalsByDateIFrame;
import GUI.StockManagement.AddCarIFrame;
import GUI.StockManagement.SearchByManufactureYearIFrame;
import GUI.StockManagement.ShowAvailableCarsIFrame;
import GUI.StockManagement.ShowCarDetailsIFrame;
import GUI.StockManagement.UpdateCarIFrame;
import PersonManagement.Employee;
import PersonManagement.Role;
import java.util.Date;

/**
 *
 * @author Sanket
 */
public class MainFrame extends javax.swing.JFrame {
    public static Store store = new Store();
    public static Employee employee = new Employee("Auckland", "02145896657", "Sanket", "employee123", Role.admin, 1, "Sanket", new Date(), "Manukau", "02214563589");
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContent = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        personManagementMenu = new javax.swing.JMenu();
        addEmployeeMenuItem = new javax.swing.JMenuItem();
        showDetailsMenuItem = new javax.swing.JMenuItem();
        updateDetailsMenuItem = new javax.swing.JMenuItem();
        stockManagementMenu = new javax.swing.JMenu();
        addCarMenuItem = new javax.swing.JMenuItem();
        showCarsAvailableMenuItem = new javax.swing.JMenuItem();
        showCarsMenuItem = new javax.swing.JMenuItem();
        searchCarByYearMenuItem = new javax.swing.JMenuItem();
        updateCarMenuItem = new javax.swing.JMenuItem();
        rentalManagementMenu = new javax.swing.JMenu();
        rentCarMenuItem = new javax.swing.JMenuItem();
        returnCarMenuItem = new javax.swing.JMenuItem();
        customerRentalsMenuItem = new javax.swing.JMenuItem();
        searchRentalsByDateMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainContent.setOpaque(false);

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N

        personManagementMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        personManagementMenu.setForeground(new java.awt.Color(102, 102, 102));
        personManagementMenu.setText("Person Management");
        personManagementMenu.setFont(new java.awt.Font("Bodoni MT", 1, 25)); // NOI18N

        addEmployeeMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        addEmployeeMenuItem.setText("Add Employee");
        addEmployeeMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addEmployeeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeMenuItemActionPerformed(evt);
            }
        });
        personManagementMenu.add(addEmployeeMenuItem);

        showDetailsMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        showDetailsMenuItem.setText("Show Person Details");
        showDetailsMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsMenuItemActionPerformed(evt);
            }
        });
        personManagementMenu.add(showDetailsMenuItem);

        updateDetailsMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        updateDetailsMenuItem.setText("Update Person Details");
        updateDetailsMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateDetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsMenuItemActionPerformed(evt);
            }
        });
        personManagementMenu.add(updateDetailsMenuItem);

        jMenuBar1.add(personManagementMenu);

        stockManagementMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        stockManagementMenu.setForeground(new java.awt.Color(102, 102, 102));
        stockManagementMenu.setText("Stock Management");
        stockManagementMenu.setFont(new java.awt.Font("Bodoni MT", 1, 25)); // NOI18N

        addCarMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        addCarMenuItem.setText("Add Car");
        addCarMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addCarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarMenuItemActionPerformed(evt);
            }
        });
        stockManagementMenu.add(addCarMenuItem);

        showCarsAvailableMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        showCarsAvailableMenuItem.setText("Show Available Cars");
        showCarsAvailableMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showCarsAvailableMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCarsAvailableMenuItemActionPerformed(evt);
            }
        });
        stockManagementMenu.add(showCarsAvailableMenuItem);

        showCarsMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        showCarsMenuItem.setText("Show  All Cars");
        showCarsMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showCarsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCarsMenuItemActionPerformed(evt);
            }
        });
        stockManagementMenu.add(showCarsMenuItem);

        searchCarByYearMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        searchCarByYearMenuItem.setText("Search by Year of Manufacture");
        searchCarByYearMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchCarByYearMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCarByYearMenuItemActionPerformed(evt);
            }
        });
        stockManagementMenu.add(searchCarByYearMenuItem);

        updateCarMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        updateCarMenuItem.setText("Update Car Details");
        updateCarMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateCarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCarMenuItemActionPerformed(evt);
            }
        });
        stockManagementMenu.add(updateCarMenuItem);

        jMenuBar1.add(stockManagementMenu);

        rentalManagementMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        rentalManagementMenu.setForeground(new java.awt.Color(102, 102, 102));
        rentalManagementMenu.setText("Rental Management");
        rentalManagementMenu.setFont(new java.awt.Font("Bodoni MT", 1, 25)); // NOI18N

        rentCarMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        rentCarMenuItem.setText("Rent Car");
        rentCarMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rentCarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarMenuItemActionPerformed(evt);
            }
        });
        rentalManagementMenu.add(rentCarMenuItem);

        returnCarMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        returnCarMenuItem.setText("Return Car");
        returnCarMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnCarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCarMenuItemActionPerformed(evt);
            }
        });
        rentalManagementMenu.add(returnCarMenuItem);

        customerRentalsMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        customerRentalsMenuItem.setText("Customer Rentals");
        customerRentalsMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        customerRentalsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRentalsMenuItemActionPerformed(evt);
            }
        });
        rentalManagementMenu.add(customerRentalsMenuItem);

        searchRentalsByDateMenuItem.setFont(new java.awt.Font("Bodoni MT", 3, 18)); // NOI18N
        searchRentalsByDateMenuItem.setText("Show Rentals by Date");
        searchRentalsByDateMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchRentalsByDateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRentalsByDateMenuItemActionPerformed(evt);
            }
        });
        rentalManagementMenu.add(searchRentalsByDateMenuItem);

        jMenuBar1.add(rentalManagementMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContent)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContent)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeMenuItemActionPerformed
        // TODO add your handling code here:
        AddEmployeeIFrame frame = new AddEmployeeIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_addEmployeeMenuItemActionPerformed

    private void showDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDetailsMenuItemActionPerformed
        // TODO add your handling code here:
        ShowPersonDetailsIFrame frame = new ShowPersonDetailsIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_showDetailsMenuItemActionPerformed

    private void addCarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarMenuItemActionPerformed
        // TODO add your handling code here:
        AddCarIFrame frame = new AddCarIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_addCarMenuItemActionPerformed

    private void updateDetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsMenuItemActionPerformed
        // TODO add your handling code here:
        UpdatePersonDetails frame = new UpdatePersonDetails();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_updateDetailsMenuItemActionPerformed

    private void showCarsAvailableMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCarsAvailableMenuItemActionPerformed
        // TODO add your handling code here:
        ShowAvailableCarsIFrame frame = new ShowAvailableCarsIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_showCarsAvailableMenuItemActionPerformed

    private void showCarsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCarsMenuItemActionPerformed
        // TODO add your handling code here:
        ShowCarDetailsIFrame frame = new ShowCarDetailsIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_showCarsMenuItemActionPerformed

    private void searchCarByYearMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCarByYearMenuItemActionPerformed
        // TODO add your handling code here:
        SearchByManufactureYearIFrame frame = new SearchByManufactureYearIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_searchCarByYearMenuItemActionPerformed

    private void rentCarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarMenuItemActionPerformed
        // TODO add your handling code here:
        RentCarIFrame frame = new RentCarIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_rentCarMenuItemActionPerformed

    private void updateCarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCarMenuItemActionPerformed
        // TODO add your handling code here:
        UpdateCarIFrame frame = new UpdateCarIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_updateCarMenuItemActionPerformed

    private void returnCarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnCarMenuItemActionPerformed
        // TODO add your handling code here:
        ReturnCarIFrame frame = new ReturnCarIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_returnCarMenuItemActionPerformed

    private void customerRentalsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRentalsMenuItemActionPerformed
        // TODO add your handling code here:
        ShowCustomerRentalsIFrame frame = new ShowCustomerRentalsIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_customerRentalsMenuItemActionPerformed

    private void searchRentalsByDateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRentalsByDateMenuItemActionPerformed
        // TODO add your handling code here:
        ShowRentalsByDateIFrame frame = new ShowRentalsByDateIFrame();
        mainContent.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_searchRentalsByDateMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCarMenuItem;
    private javax.swing.JMenuItem addEmployeeMenuItem;
    private javax.swing.JMenuItem customerRentalsMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane mainContent;
    private javax.swing.JMenu personManagementMenu;
    private javax.swing.JMenuItem rentCarMenuItem;
    private javax.swing.JMenu rentalManagementMenu;
    private javax.swing.JMenuItem returnCarMenuItem;
    private javax.swing.JMenuItem searchCarByYearMenuItem;
    private javax.swing.JMenuItem searchRentalsByDateMenuItem;
    private javax.swing.JMenuItem showCarsAvailableMenuItem;
    private javax.swing.JMenuItem showCarsMenuItem;
    private javax.swing.JMenuItem showDetailsMenuItem;
    private javax.swing.JMenu stockManagementMenu;
    private javax.swing.JMenuItem updateCarMenuItem;
    private javax.swing.JMenuItem updateDetailsMenuItem;
    // End of variables declaration//GEN-END:variables
}
